# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:
- job: 'Default'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    maxParallel: 10
    matrix:
      Python36:
        PYTHON_VERSION: '3.6'
        ARCH: 'x86'
        PIP_FLAGS: ''
      Python36-x64:
        PYTHON_VERSION: '3.6'
        ARCH: 'x64'
        PIP_FLAGS: ''
      Python37:
        PYTHON_VERSION: '3.7'
        ARCH: 'x86'
        PIP_FLAGS: ''
      Python37-x64:
        PYTHON_VERSION: '3.7'
        ARCH: 'x64'
        PIP_FLAGS: ''
  continueOnError: false
  timeoutInMinutes: 60

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- powershell: |
    Write-Host "##vso[task.setvariable variable=PATH;]${env:PYTHON};${env:PYTHON}\Scripts;${env:PATH}";
  displayName: 'Add Python paths to PATH'

- script: |
    python -m pip install --retries 3 -U pip setuptools setuptools-scm
    pip install --retries 3 -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    git submodule init
    git submodule update
    CFLAGS="" python setup.py build_ext -i
  displayName: 'Compile package'

- script: |
    pip install pytest pytest-azurepipelines
    PYTHONPATH=. pytest -v
  displayName: 'pytest'
